'use client';

import { useState, useRef, useEffect } from 'react';
import { MessageCircle, X, ChevronLeft, Send, Loader2 } from 'lucide-react';
import { toast } from 'sonner';

// ─── FAQ data ─────────────────────────────────────────────────────────────────

const FAQ: { q: string; a: string }[] = [
  {
    q: 'What is WebAnalyzer?',
    a: 'WebAnalyzer is an automated SaaS platform that analyzes any website for performance, accessibility, SEO, and console errors — then delivers AI-powered recommendations in a detailed report. You get a full Lighthouse audit, WCAG compliance check, and Claude AI insights in under 60 seconds.',
  },
  {
    q: 'How does an analysis work?',
    a: 'You enter a URL and click Analyze. Our engine visits the page, captures a full-page screenshot, runs a Lighthouse audit, checks for WCAG accessibility violations, collects console errors, and crawls up to 5 internal pages. Claude AI then interprets all results and generates prioritized recommendations. The full process takes under 60 seconds.',
  },
  {
    q: 'How many free analyses do I get?',
    a: 'Every new account includes 3 free analyses — no credit card required. Free credits do not expire. Once you run out, you can upgrade to the Pro plan (100 analyses/month) or the Agency plan (unlimited).',
  },
  {
    q: 'What is included in the Pro plan?',
    a: 'The Pro plan is $29/month and includes 100 analyses per month, PDF report export, design screenshot comparison, site crawl (up to 5 pages), scheduled monitoring with email alerts, API access, and webhook integrations.',
  },
  {
    q: 'What is the Agency plan?',
    a: 'The Agency plan is $99/month and includes everything in Pro, plus unlimited analyses, white-label PDF reports with your own branding, team member seats, priority support, and higher API rate limits.',
  },
  {
    q: 'How does billing work?',
    a: 'All plans are billed monthly via Stripe. You can upgrade, downgrade, or cancel at any time from the Settings → Billing page. When you upgrade, you are charged immediately and your credit balance resets. When you cancel, you keep access until the end of your current billing period.',
  },
  {
    q: 'What is your refund policy?',
    a: 'We offer a 7-day money-back guarantee. If you are not satisfied within the first 7 days of a paid subscription, contact us and we will issue a full refund — no questions asked. Refunds outside this window are reviewed on a case-by-case basis.',
  },
  {
    q: 'How long does an analysis take?',
    a: 'Most analyses complete in 30–60 seconds. Complex pages or sites with slow servers may take up to 90 seconds. You can watch the real-time progress on the analysis status page — it shows each step as it completes.',
  },
  {
    q: 'What is the public API?',
    a: 'The public REST API lets you trigger analyses and retrieve reports programmatically using API keys with a `wa_live_` prefix. It is available on Pro and Agency plans. Full documentation is at /docs, including endpoint references, authentication details, and code examples.',
  },
  {
    q: 'What does "AI Insights" mean?',
    a: 'AI Insights are generated by Claude (Anthropic\'s AI). Claude analyzes your site screenshot visually for UX and layout issues, interprets Lighthouse scores into plain-English recommendations, and explains accessibility violations with code fix examples. You also get a list of quick wins — small changes with the highest impact.',
  },
];

// ─── Types ─────────────────────────────────────────────────────────────────────

type Screen =
  | 'home'
  | 'faq-answer'
  | 'contact-info'
  | 'contact-message'
  | 'contact-sent';

interface ContactInfo {
  name: string;
  email: string;
  phone: string;
}

// ─── Component ────────────────────────────────────────────────────────────────

export function SupportChat() {
  const [open, setOpen] = useState(false);
  const [screen, setScreen] = useState<Screen>('home');
  const [activeFaq, setActiveFaq] = useState<{ q: string; a: string } | null>(null);
  const [contact, setContact] = useState<ContactInfo>({ name: '', email: '', phone: '' });
  const [message, setMessage] = useState('');
  const [sending, setSending] = useState(false);
  const [contactErrors, setContactErrors] = useState<Partial<ContactInfo>>({});
  const panelRef = useRef<HTMLDivElement>(null);

  // Close on outside click
  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      if (panelRef.current && !panelRef.current.contains(e.target as Node)) {
        setOpen(false);
      }
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [open]);

  const toggleOpen = () => {
    setOpen((v) => {
      if (!v) setScreen('home');
      return !v;
    });
  };

  const openFaq = (item: { q: string; a: string }) => {
    setActiveFaq(item);
    setScreen('faq-answer');
  };

  const validateContact = (): boolean => {
    const errs: Partial<ContactInfo> = {};
    if (!contact.name.trim()) errs.name = 'Required';
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(contact.email)) errs.email = 'Invalid email';
    if (!contact.phone.trim()) errs.phone = 'Required';
    setContactErrors(errs);
    return Object.keys(errs).length === 0;
  };

  const handleContactNext = () => {
    if (validateContact()) setScreen('contact-message');
  };

  const handleSend = async () => {
    if (!message.trim()) return;
    setSending(true);
    try {
      const res = await fetch('/api/support/contact', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ...contact, message }),
      });
      if (!res.ok) throw new Error('Failed to send');
      setScreen('contact-sent');
    } catch {
      toast.error('Failed to send message. Please try again.');
    } finally {
      setSending(false);
    }
  };

  const reset = () => {
    setScreen('home');
    setContact({ name: '', email: '', phone: '' });
    setMessage('');
    setContactErrors({});
    setActiveFaq(null);
  };

  return (
    <div className="fixed bottom-6 right-6 z-50 flex flex-col items-end gap-3">
      {/* Chat panel */}
      {open && (
        <div
          ref={panelRef}
          className="w-[360px] max-h-[560px] flex flex-col rounded-2xl border border-border bg-card shadow-2xl overflow-hidden"
          style={{ boxShadow: '0 8px 40px rgba(99,102,241,0.18)' }}
        >
          {/* Header */}
          <div className="flex items-center justify-between px-4 py-3 bg-gradient-to-r from-indigo-600 to-violet-600 shrink-0">
            <div className="flex items-center gap-3">
              {screen !== 'home' && (
                <button
                  onClick={() => setScreen(screen === 'contact-message' ? 'contact-info' : 'home')}
                  className="text-white/80 hover:text-white transition-colors mr-1"
                  aria-label="Back"
                >
                  <ChevronLeft className="h-4 w-4" />
                </button>
              )}
              <div className="h-8 w-8 rounded-full bg-white/20 flex items-center justify-center shrink-0">
                <span className="text-sm font-bold text-white">WA</span>
              </div>
              <div>
                <p className="text-sm font-semibold text-white leading-tight">WebAnalyzer Support</p>
                <p className="text-xs text-white/70">We typically reply instantly</p>
              </div>
            </div>
            <button onClick={() => setOpen(false)} className="text-white/80 hover:text-white transition-colors" aria-label="Close">
              <X className="h-4 w-4" />
            </button>
          </div>

          {/* Body */}
          <div className="flex-1 overflow-y-auto">

            {/* ── Home screen ── */}
            {screen === 'home' && (
              <div className="p-4 space-y-4">
                <div className="bg-secondary/50 rounded-xl p-3">
                  <p className="text-sm text-foreground font-medium mb-0.5">Hi there! 👋</p>
                  <p className="text-xs text-muted-foreground">
                    How can we help you today? Pick a question or contact us directly.
                  </p>
                </div>

                <div>
                  <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">
                    Frequently Asked Questions
                  </p>
                  <div className="space-y-1.5">
                    {FAQ.map((item) => (
                      <button
                        key={item.q}
                        onClick={() => openFaq(item)}
                        className="w-full text-left text-sm px-3 py-2.5 rounded-lg border border-border bg-background hover:bg-accent hover:border-indigo-500/30 transition-colors"
                      >
                        {item.q}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="border-t border-border pt-3">
                  <p className="text-xs text-muted-foreground mb-2">
                    Can&apos;t find what you need?
                  </p>
                  <button
                    onClick={() => setScreen('contact-info')}
                    className="w-full text-sm font-medium px-3 py-2.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white transition-colors"
                  >
                    Chat with us
                  </button>
                </div>
              </div>
            )}

            {/* ── FAQ answer ── */}
            {screen === 'faq-answer' && activeFaq && (
              <div className="p-4 space-y-3">
                <div className="rounded-xl bg-secondary/50 px-3 py-2.5">
                  <p className="text-xs font-semibold text-indigo-400 mb-1">Your question</p>
                  <p className="text-sm font-medium text-foreground">{activeFaq.q}</p>
                </div>
                <div className="rounded-xl border border-border px-3 py-2.5">
                  <p className="text-xs font-semibold text-muted-foreground mb-1">Answer</p>
                  <p className="text-sm text-foreground leading-relaxed">{activeFaq.a}</p>
                </div>
                <div className="pt-1 border-t border-border">
                  <p className="text-xs text-muted-foreground mb-2">Still have questions?</p>
                  <button
                    onClick={() => setScreen('contact-info')}
                    className="w-full text-sm font-medium px-3 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white transition-colors"
                  >
                    Chat with us
                  </button>
                </div>
              </div>
            )}

            {/* ── Contact info form ── */}
            {screen === 'contact-info' && (
              <div className="p-4 space-y-4">
                <div className="bg-secondary/50 rounded-xl p-3">
                  <p className="text-sm font-medium text-foreground mb-0.5">Before we connect</p>
                  <p className="text-xs text-muted-foreground">
                    Please share your contact details so we can follow up if needed.
                  </p>
                </div>
                <div className="space-y-3">
                  <div>
                    <label className="text-xs font-medium text-muted-foreground block mb-1">
                      Full name <span className="text-red-400">*</span>
                    </label>
                    <input
                      type="text"
                      value={contact.name}
                      onChange={(e) => setContact((c) => ({ ...c, name: e.target.value }))}
                      placeholder="John Smith"
                      className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground/50 focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-indigo-500/50 transition-colors"
                    />
                    {contactErrors.name && (
                      <p className="text-xs text-red-400 mt-1">{contactErrors.name}</p>
                    )}
                  </div>
                  <div>
                    <label className="text-xs font-medium text-muted-foreground block mb-1">
                      Email <span className="text-red-400">*</span>
                    </label>
                    <input
                      type="email"
                      value={contact.email}
                      onChange={(e) => setContact((c) => ({ ...c, email: e.target.value }))}
                      placeholder="you@example.com"
                      className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground/50 focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-indigo-500/50 transition-colors"
                    />
                    {contactErrors.email && (
                      <p className="text-xs text-red-400 mt-1">{contactErrors.email}</p>
                    )}
                  </div>
                  <div>
                    <label className="text-xs font-medium text-muted-foreground block mb-1">
                      Phone <span className="text-red-400">*</span>
                    </label>
                    <input
                      type="tel"
                      value={contact.phone}
                      onChange={(e) => setContact((c) => ({ ...c, phone: e.target.value }))}
                      placeholder="+1 (555) 000-0000"
                      className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground/50 focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-indigo-500/50 transition-colors"
                    />
                    {contactErrors.phone && (
                      <p className="text-xs text-red-400 mt-1">{contactErrors.phone}</p>
                    )}
                  </div>
                  <button
                    onClick={handleContactNext}
                    className="w-full text-sm font-medium px-3 py-2.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white transition-colors mt-1"
                  >
                    Continue →
                  </button>
                </div>
              </div>
            )}

            {/* ── Contact message ── */}
            {screen === 'contact-message' && (
              <div className="p-4 space-y-3">
                <div className="bg-secondary/50 rounded-xl p-3">
                  <p className="text-sm font-medium text-foreground mb-0.5">Hi, {contact.name}!</p>
                  <p className="text-xs text-muted-foreground">
                    Type your question below and we&apos;ll get back to you as soon as possible.
                  </p>
                </div>
                <div>
                  <textarea
                    value={message}
                    onChange={(e) => setMessage(e.target.value)}
                    placeholder="Describe your question or issue..."
                    rows={5}
                    className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground/50 focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-indigo-500/50 transition-colors resize-none"
                  />
                </div>
                <button
                  onClick={handleSend}
                  disabled={sending || !message.trim()}
                  className="w-full flex items-center justify-center gap-2 text-sm font-medium px-3 py-2.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed text-white transition-colors"
                >
                  {sending ? (
                    <><Loader2 className="h-4 w-4 animate-spin" /> Sending…</>
                  ) : (
                    <><Send className="h-4 w-4" /> Send message</>
                  )}
                </button>
              </div>
            )}

            {/* ── Sent confirmation ── */}
            {screen === 'contact-sent' && (
              <div className="p-6 flex flex-col items-center text-center gap-3">
                <div className="h-14 w-14 rounded-full bg-emerald-500/15 flex items-center justify-center">
                  <span className="text-2xl">✓</span>
                </div>
                <p className="text-base font-semibold text-foreground">Message sent!</p>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Thanks, {contact.name}. We&apos;ve received your message and will reply to{' '}
                  <span className="text-foreground font-medium">{contact.email}</span> shortly.
                </p>
                <button
                  onClick={reset}
                  className="mt-2 text-sm text-indigo-400 hover:text-indigo-300 transition-colors underline"
                >
                  Back to FAQ
                </button>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Floating button */}
      <button
        onClick={toggleOpen}
        aria-label={open ? 'Close support chat' : 'Open support chat'}
        className="h-14 w-14 rounded-full bg-gradient-to-br from-indigo-500 to-violet-600 shadow-lg hover:shadow-indigo-500/40 hover:scale-105 active:scale-95 transition-all duration-200 flex items-center justify-center"
        style={{ boxShadow: '0 4px 24px rgba(99,102,241,0.4)' }}
      >
        {open ? (
          <X className="h-5 w-5 text-white" />
        ) : (
          <MessageCircle className="h-5 w-5 text-white" />
        )}
      </button>
    </div>
  );
}
