import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { createServiceRoleClient } from '@/lib/supabase/server';
import { getSignedUrlOrNull } from '@/lib/supabase/storage';
import { PerformanceSection } from '@/components/reports/PerformanceSection';
import { EAAComplianceSection } from '@/components/reports/EAAComplianceSection';
import { AccessibilitySection } from '@/components/reports/AccessibilitySection';
import { ConsoleErrorsSection } from '@/components/reports/ConsoleErrorsSection';
import { AIInsightsSection } from '@/components/reports/AIInsightsSection';
import { ScreenshotViewer } from '@/components/reports/ScreenshotViewer';
import { DesignComparisonSection } from '@/components/reports/DesignComparisonSection';
import { ShareReportHeader } from '@/components/reports/ShareReportHeader';
import { LLMReadinessSection } from '@/components/reports/LLMReadinessSection';
import { CrawledPagesSection } from '@/components/reports/CrawledPagesSection';
import { SecurityHeadersSection } from '@/components/reports/SecurityHeadersSection';
import { ResourceAuditSection } from '@/components/reports/ResourceAuditSection';
import { ScoreBreakdownSection } from '@/components/reports/ScoreBreakdownSection';
import { SEOSection } from '@/components/reports/SEOSection';
import { BestPracticesSection } from '@/components/reports/BestPracticesSection';
import type { Analysis } from '@/types/analysis';

export async function generateMetadata(props: { params: Promise<{ id: string }> }): Promise<Metadata> {
  const params = await props.params;
  const supabase = createServiceRoleClient();
  const { data } = await (supabase
    .from('analyses') as any)
    .select('url')
    .eq('id', params.id)
    .eq('is_public', true)
    .single();

  if (!data) return { title: 'Report Not Found' };

  return {
    title: `Site Report — ${data.url}`,
    description: `Website analysis report for ${data.url}, generated by WebAnalyzer.`,
  };
}

// Cache public reports for 1 hour — they are immutable once created
export const revalidate = 3600;

export default async function PublicReportPage(props: { params: Promise<{ id: string }> }) {
  const params = await props.params;
  // Use service role so RLS doesn't block — we manually check is_public
  const supabase = createServiceRoleClient();

  const { data: raw } = await (supabase
    .from('analyses') as any)
    .select('*')
    .eq('id', params.id)
    .eq('is_public', true)
    .eq('status', 'completed')
    .single();

  const analysis = raw as unknown as Analysis | null;
  if (!analysis) notFound();

  // Resolve storage paths → time-limited signed URLs (1 h).
  // Service role client can sign files in the private screenshots bucket.
  const [screenshotSignedUrl, designSignedUrl] = await Promise.all([
    getSignedUrlOrNull(supabase, analysis.screenshot_url),
    getSignedUrlOrNull(supabase, analysis.design_screenshot_url),
  ]);

  return (
    <div className="min-h-screen bg-background">
      {/* Public header */}
      <header className="border-b border-border bg-background/80 backdrop-blur sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-4 md:px-6 h-14 flex items-center justify-between">
          <span className="font-bold text-lg text-gradient">WebAnalyzer</span>
          <a
            href="/"
            className="text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            Get your free report →
          </a>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 md:px-6 py-8 space-y-6 md:space-y-10">
        <ShareReportHeader analysis={analysis} />
        <ScreenshotViewer url={screenshotSignedUrl} siteUrl={analysis.url} />
        {analysis.lighthouse_scores && (
          <PerformanceSection scores={analysis.lighthouse_scores as any} />
        )}
        {(analysis.lighthouse_scores as any)?.scoreBreakdown && (
          <ScoreBreakdownSection
            breakdown={(analysis.lighthouse_scores as any).scoreBreakdown}
            scores={{
              performance: (analysis.lighthouse_scores as any).performance,
              bestPractices: (analysis.lighthouse_scores as any).bestPractices,
              seo: (analysis.lighthouse_scores as any).seo,
              accessibility: (analysis.lighthouse_scores as any).accessibility,
            }}
          />
        )}
        <SecurityHeadersSection
          securityHeaders={(analysis.lighthouse_scores as any)?.securityHeaders}
          crawledPages={analysis.crawl_pages as any}
        />
        <ResourceAuditSection resourceAudit={(analysis.network_requests as any)?.resourceAudit} />
        {analysis.accessibility_issues && (
          <EAAComplianceSection
            accessibilityIssues={(analysis.accessibility_issues as any) ?? undefined}
          />
        )}
        {(analysis.lighthouse_scores as any)?.accessibilityAudit ? (
          <AccessibilitySection
            accessibilityAudit={(analysis.lighthouse_scores as any).accessibilityAudit}
            aiInsights={(analysis.ai_insights as any)?.accessibility?.interpretedIssues ?? null}
          />
        ) : analysis.accessibility_issues ? (
          <AccessibilitySection
            issues={analysis.accessibility_issues as any}
            aiInsights={(analysis.ai_insights as any)?.accessibility?.interpretedIssues ?? null}
          />
        ) : null}
        <SEOSection
          seoAudit={(analysis.lighthouse_scores as any)?.seoAudit ?? null}
          legacyScore={analysis.lighthouse_scores?.seo}
          legacyChecks={(analysis.lighthouse_scores as any)?.scoreBreakdown?.seo}
        />
        <BestPracticesSection
          bestPracticesAudit={(analysis.lighthouse_scores as any)?.bestPracticesAudit ?? null}
          legacyScore={analysis.lighthouse_scores?.bestPractices}
          legacyChecks={(analysis.lighthouse_scores as any)?.scoreBreakdown?.bestPractices}
        />
        {analysis.console_errors && (
          <ConsoleErrorsSection errors={analysis.console_errors as any} />
        )}
        {analysis.ai_insights && (
          <AIInsightsSection insights={analysis.ai_insights as any} />
        )}
        {designSignedUrl && (
          <DesignComparisonSection
            designComparison={(analysis.design_comparison as any) ?? undefined}
            designScreenshotUrl={designSignedUrl}
            screenshotUrl={screenshotSignedUrl ?? undefined}
          />
        )}
        {analysis.lighthouse_scores && (
          <LLMReadinessSection scores={analysis.lighthouse_scores as any} />
        )}
        {analysis.crawl_pages && (
          <CrawledPagesSection crawledPages={analysis.crawl_pages as any} />
        )}

        {/* CTA footer */}
        <div className="bg-card border border-border rounded-xl p-6 md:p-8 text-center space-y-4">
          <p className="text-lg font-semibold text-foreground">
            Want a report like this for your site?
          </p>
          <p className="text-muted-foreground text-sm">
            WebAnalyzer gives you performance, accessibility, AI insights, and more — free to start.
          </p>
          <a
            href="/signup"
            className="inline-flex items-center gap-1 rounded-lg bg-gradient-to-r from-indigo-500 to-violet-500 px-6 py-2.5 text-sm font-medium text-white hover:opacity-90 transition-opacity"
          >
            Analyze your site free →
          </a>
        </div>
      </main>
    </div>
  );
}
