import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { createServiceRoleClient } from '@/lib/supabase/server';
import { PerformanceSection } from '@/components/reports/PerformanceSection';
import { EAAComplianceSection } from '@/components/reports/EAAComplianceSection';
import { AccessibilitySection } from '@/components/reports/AccessibilitySection';
import { ConsoleErrorsSection } from '@/components/reports/ConsoleErrorsSection';
import { AIInsightsSection } from '@/components/reports/AIInsightsSection';
import { ScreenshotViewer } from '@/components/reports/ScreenshotViewer';
import { DesignComparisonSection } from '@/components/reports/DesignComparisonSection';
import { ShareReportHeader } from '@/components/reports/ShareReportHeader';
import type { Analysis } from '@/types/analysis';

export async function generateMetadata(
  { params }: { params: { id: string } }
): Promise<Metadata> {
  const supabase = createServiceRoleClient();
  const { data } = await (supabase
    .from('analyses') as any)
    .select('url')
    .eq('id', params.id)
    .eq('is_public', true)
    .single();

  if (!data) return { title: 'Report Not Found' };

  return {
    title: `Site Report — ${data.url}`,
    description: `Website analysis report for ${data.url}, generated by WebAnalyzer.`,
  };
}

export default async function PublicReportPage({ params }: { params: { id: string } }) {
  // Use service role so RLS doesn't block — we manually check is_public
  const supabase = createServiceRoleClient();

  const { data: raw } = await (supabase
    .from('analyses') as any)
    .select('*')
    .eq('id', params.id)
    .eq('is_public', true)
    .eq('status', 'completed')
    .single();

  const analysis = raw as unknown as Analysis | null;
  if (!analysis) notFound();

  return (
    <div className="min-h-screen bg-background">
      {/* Public header — branding + no auth controls */}
      <header className="border-b bg-background/80 backdrop-blur sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-4 md:px-6 h-14 flex items-center justify-between">
          <span className="font-bold text-lg">WebAnalyzer</span>
          <a
            href="/"
            className="text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            Get your free report →
          </a>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 md:px-6 py-8 space-y-6 md:space-y-10">
        <ShareReportHeader analysis={analysis} />
        <ScreenshotViewer url={analysis.screenshot_url} siteUrl={analysis.url} />
        {analysis.lighthouse_scores && (
          <PerformanceSection scores={analysis.lighthouse_scores as any} />
        )}
        {analysis.accessibility_issues && (
          <EAAComplianceSection
            issues={(analysis.accessibility_issues as any) ?? []}
            accessibilityScore={(analysis.lighthouse_scores as any)?.accessibility ?? null}
          />
        )}
        {analysis.accessibility_issues && (
          <AccessibilitySection
            issues={analysis.accessibility_issues as any}
            aiInsights={(analysis.ai_insights as any)?.accessibility?.interpretedIssues ?? null}
          />
        )}
        {analysis.console_errors && (
          <ConsoleErrorsSection errors={analysis.console_errors as any} />
        )}
        {analysis.ai_insights && (
          <AIInsightsSection insights={analysis.ai_insights as any} />
        )}
        {analysis.design_comparison && (
          <DesignComparisonSection
            comparison={analysis.design_comparison as any}
            designScreenshotUrl={analysis.design_screenshot_url ?? null}
            liveScreenshotUrl={analysis.screenshot_url ?? null}
          />
        )}

        {/* CTA footer */}
        <div className="rounded-xl border bg-muted/40 p-6 md:p-8 text-center space-y-3">
          <p className="text-lg font-semibold">Want a report like this for your site?</p>
          <p className="text-muted-foreground text-sm">
            WebAnalyzer gives you performance, accessibility, AI insights, and more — free to start.
          </p>
          <a
            href="/signup"
            className="inline-block rounded-md bg-primary px-6 py-2.5 text-sm font-medium text-primary-foreground hover:bg-primary/90 transition-colors"
          >
            Analyze your site free →
          </a>
        </div>
      </main>
    </div>
  );
}
