/**
 * Fix Request delivery channel adapters.
 *
 * Each adapter receives a fully prepared MessageContext and handles
 * the channel-specific delivery mechanism.
 *
 * SECURITY constraints:
 *  - Email and phone numbers are consumed here, never logged
 *  - WhatsApp/Telegram adapters only produce links — the user clicks them
 *  - Webhook payloads are HMAC-signed via the existing deliver.ts module
 *  - External links use scoped tokens generated by the public-link module
 *  - Attachment content is never embedded in payloads; only signed URLs
 *  - All external delivery records the provider evidence level, not content
 */

import type { FixRequestDeliveryChannel, DeliveryEvidenceLevel } from '@/types/fix-request';
import type { MessageContext, FixRequestWebhookPayload } from './message-generator';
import {
  buildEmailMessage,
  buildWhatsAppLink,
  buildTelegramShareLink,
  buildWebhookPayload,
  buildSlackPayload,
} from './message-generator';
import { createLogger } from '@/lib/logger';

const logger = createLogger({ module: 'fix-request/channel-adapters' });

// ── Result types ──────────────────────────────────────────────────────────────

export interface ChannelDeliveryResult {
  channel:        FixRequestDeliveryChannel;
  status:         'accepted' | 'delivered' | 'failed' | 'skipped' | 'link_generated';
  evidenceLevel:  DeliveryEvidenceLevel;
  providerRef?:   string;
  httpStatus?:    number;
  link?:          string;     // for link-based channels; returned to caller, not logged
  errorSummary?:  string;     // short error; never includes raw response body or secrets
}

// ── Email delivery ────────────────────────────────────────────────────────────

export async function deliverViaEmail(
  recipientEmail: string,
  ctx: MessageContext,
  fixRequestId: string,
  sendFn: (to: string, subject: string, html: string, text: string) => Promise<{ id?: string }>,
): Promise<ChannelDeliveryResult> {
  const msg = buildEmailMessage(ctx);

  // SECURITY: recipientEmail consumed here — not logged
  try {
    const result = await sendFn(recipientEmail, msg.subject, msg.html, msg.text);
    logger.info('fix_request_email_sent', { fixRequestId, channel: 'email', ref: result.id ?? 'unknown' });
    return {
      channel:       'email',
      status:        'accepted',
      evidenceLevel: 'accepted_by_provider',
      providerRef:   result.id,
    };
  } catch (err: unknown) {
    const summary = err instanceof Error ? err.message.slice(0, 200) : 'Email send failed';
    logger.error('fix_request_email_failed', { fixRequestId, errorSummary: summary });
    return {
      channel:       'email',
      status:        'failed',
      evidenceLevel: 'prepared',
      errorSummary:  summary,
    };
  }
}

// ── WhatsApp click-to-chat link ───────────────────────────────────────────────

export function generateWhatsAppLink(
  phoneE164: string,
  ctx: MessageContext,
): ChannelDeliveryResult {
  const link = buildWhatsAppLink(phoneE164, ctx);
  // Phone number consumed here; link contains encoded text only
  return {
    channel:       'whatsapp_link',
    status:        'link_generated',
    evidenceLevel: 'prepared',
    link,
  };
}

// ── Telegram share link ───────────────────────────────────────────────────────

export function generateTelegramShareLink(ctx: MessageContext): ChannelDeliveryResult {
  const link = buildTelegramShareLink(ctx);
  return {
    channel:       'telegram_share',
    status:        'link_generated',
    evidenceLevel: 'prepared',
    link,
  };
}

// ── Webhook delivery (reuses existing deliver.ts) ─────────────────────────────

export async function deliverViaWebhook(
  webhookUrl: string,
  webhookSecret: string,
  fixRequestId: string,
  event: FixRequestWebhookPayload['event'],
  ctx: MessageContext,
  status: string,
  isSlack: boolean,
): Promise<ChannelDeliveryResult> {
  const payload = buildWebhookPayload(fixRequestId, event, ctx, status);
  const body = isSlack ? buildSlackPayload(ctx) : payload;

  // SECURITY: webhookSecret is consumed here and never logged
  if (!webhookSecret) {
    logger.warn('fix_request_webhook_skipped_no_secret', { fixRequestId });
    return {
      channel:       'webhook',
      status:        'skipped',
      evidenceLevel: 'prepared',
      errorSummary:  'Webhook secret is empty — delivery skipped.',
    };
  }

  const bodyStr = JSON.stringify(body);

  let signature: string;
  try {
    const encoder = new TextEncoder();
    const keyData = encoder.encode(webhookSecret);
    const msgData = encoder.encode(bodyStr);
    const cryptoKey = await crypto.subtle.importKey('raw', keyData, { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
    const sig = await crypto.subtle.sign('HMAC', cryptoKey, msgData);
    signature = 'sha256=' + Array.from(new Uint8Array(sig)).map((b) => b.toString(16).padStart(2, '0')).join('');
  } catch (err: unknown) {
    const summary = err instanceof Error ? err.message.slice(0, 100) : 'HMAC error';
    return { channel: 'webhook', status: 'failed', evidenceLevel: 'prepared', errorSummary: summary };
  }

  try {
    const res = await fetch(webhookUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-WebAnalyzer-Signature': signature,
        'X-Fix-Request-Id': fixRequestId,
      },
      body: bodyStr,
      signal: AbortSignal.timeout(10_000),
    });
    logger.info('fix_request_webhook_sent', { fixRequestId, httpStatus: res.status });
    if (res.ok) {
      return { channel: 'webhook', status: 'accepted', evidenceLevel: 'accepted_by_provider', httpStatus: res.status };
    }
    return { channel: 'webhook', status: 'failed', evidenceLevel: 'prepared', httpStatus: res.status, errorSummary: `HTTP ${res.status}` };
  } catch (err: unknown) {
    const summary = err instanceof Error ? err.message.slice(0, 200) : 'Network error';
    logger.error('fix_request_webhook_failed', { fixRequestId, errorSummary: summary });
    return { channel: 'webhook', status: 'failed', evidenceLevel: 'prepared', errorSummary: summary };
  }
}

// ── Internal assignment (in-app; no network call) ────────────────────────────

export function deliverViaInternalAssignment(
  assigneeUserId: string,
  fixRequestId: string,
): ChannelDeliveryResult {
  logger.info('fix_request_assigned', { fixRequestId, assigneeUserId });
  return {
    channel:       'internal_assignment',
    status:        'delivered',
    evidenceLevel: 'recipient_acknowledged',
    providerRef:   assigneeUserId,
  };
}

// ── External link (scoped token; generated separately, tracked here) ──────────

export function recordExternalLinkGenerated(
  fixRequestId: string,
  tokenId: string,
): ChannelDeliveryResult {
  logger.info('fix_request_external_link_created', { fixRequestId, tokenId });
  return {
    channel:       'external_link',
    status:        'link_generated',
    evidenceLevel: 'prepared',
    providerRef:   tokenId,
  };
}

// ── Route to correct adapter ──────────────────────────────────────────────────

export type ChannelAdapterOptions = {
  channel:       FixRequestDeliveryChannel;
  ctx:           MessageContext;
  fixRequestId:  string;
  // Channel-specific
  recipientEmail?:  string;
  phoneE164?:       string;
  webhookUrl?:      string;
  webhookSecret?:   string;
  webhookStatus?:   string;
  webhookEvent?:    FixRequestWebhookPayload['event'];
  isSlackWebhook?:  boolean;
  assigneeUserId?:  string;
  externalTokenId?: string;
  emailSendFn?: (to: string, subject: string, html: string, text: string) => Promise<{ id?: string }>;
};

export async function deliverToChannel(opts: ChannelAdapterOptions): Promise<ChannelDeliveryResult> {
  switch (opts.channel) {
    case 'email':
      if (!opts.recipientEmail || !opts.emailSendFn) {
        return { channel: 'email', status: 'skipped', evidenceLevel: 'prepared', errorSummary: 'Missing email or send function' };
      }
      return deliverViaEmail(opts.recipientEmail, opts.ctx, opts.fixRequestId, opts.emailSendFn);

    case 'whatsapp_link':
      if (!opts.phoneE164) {
        return { channel: 'whatsapp_link', status: 'skipped', evidenceLevel: 'prepared', errorSummary: 'Missing phone number' };
      }
      return generateWhatsAppLink(opts.phoneE164, opts.ctx);

    case 'telegram_share':
      return generateTelegramShareLink(opts.ctx);

    case 'webhook':
      if (!opts.webhookUrl || !opts.webhookSecret) {
        return { channel: 'webhook', status: 'skipped', evidenceLevel: 'prepared', errorSummary: 'Missing webhook URL or secret' };
      }
      return deliverViaWebhook(
        opts.webhookUrl,
        opts.webhookSecret,
        opts.fixRequestId,
        opts.webhookEvent ?? 'fix_request.created',
        opts.ctx,
        opts.webhookStatus ?? 'sent',
        opts.isSlackWebhook ?? false,
      );

    case 'internal_assignment':
      if (!opts.assigneeUserId) {
        return { channel: 'internal_assignment', status: 'skipped', evidenceLevel: 'prepared', errorSummary: 'Missing assignee user ID' };
      }
      return deliverViaInternalAssignment(opts.assigneeUserId, opts.fixRequestId);

    case 'external_link':
      if (!opts.externalTokenId) {
        return { channel: 'external_link', status: 'skipped', evidenceLevel: 'prepared', errorSummary: 'Missing token ID' };
      }
      return recordExternalLinkGenerated(opts.fixRequestId, opts.externalTokenId);

    case 'internal_chat':
      // Internal chat messages are created directly in fix_request_messages
      logger.info('fix_request_internal_chat_prepared', { fixRequestId: opts.fixRequestId });
      return { channel: 'internal_chat', status: 'delivered', evidenceLevel: 'recipient_viewed' };

    case 'whatsapp_business':
    case 'telegram_bot':
      return {
        channel:       opts.channel,
        status:        'skipped',
        evidenceLevel: 'prepared',
        errorSummary:  `${opts.channel} requires provider API configuration (post-MVP feature).`,
      };
  }
}
