'use client';

import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { AlertTriangle } from 'lucide-react';
import { toast } from 'sonner';

/** Displayed prominently — must never be removed. */
const DRAFT_DISCLAIMER =
  'DRAFT — Review before publication. This statement was generated by WebScore as a starting template. It must be reviewed by a qualified person before publication. WebScore does not provide legal advice. Automated testing alone cannot certify conformance with accessibility standards.';

interface StatementContent {
  organizationName?:    string;
  websiteUrl?:          string;
  conformanceStatus?:   string;
  technicalFindings?:   string;
  nonAccessibleContent?:string;
  feedbackMechanism?:   string;
  enforcementProcedure?:string;
  additionalNotes?:     string;
}

interface Statement {
  id:      string;
  status:  string;
  content: StatementContent;
}

interface Props {
  statement:   Statement;
  onSaved?:    (updated: Statement) => void;
}

const STATUS_LABELS: Record<string, string> = {
  draft:             'Draft',
  ready_for_review:  'Ready for Review',
  approved:          'Approved',
  published:         'Published',
  review_due:        'Review Due',
  archived:          'Archived',
};

export function AccessibilityStatementEditor({ statement, onSaved }: Props) {
  const [content,  setContent]  = useState<StatementContent>(statement.content ?? {});
  const [status,   setStatus]   = useState(statement.status);
  const [preview,  setPreview]  = useState(false);
  const [saving,   setSaving]   = useState(false);

  const update = (field: keyof StatementContent, value: string) => {
    setContent((prev) => ({ ...prev, [field]: value }));
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      const res = await fetch(`/api/accessibility/statements/${statement.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ content, status }),
      });

      if (!res.ok) {
        const d = await res.json().catch(() => ({}));
        throw new Error(d.error ?? 'Save failed');
      }

      const updated = await res.json();
      toast.success('Statement saved.');
      onSaved?.(updated);
    } catch (err: unknown) {
      toast.error(err instanceof Error ? err.message : 'Save failed');
    } finally {
      setSaving(false);
    }
  };

  const FIELDS: { key: keyof StatementContent; label: string; hint: string; multiline?: boolean }[] = [
    { key: 'organizationName',    label: 'Organization name',        hint: 'Your organization or company name' },
    { key: 'websiteUrl',          label: 'Website URL',              hint: 'The URL this statement covers' },
    { key: 'conformanceStatus',   label: 'Conformance status',       hint: 'e.g. "Partially conforms to WCAG 2.1 AA"', multiline: true },
    { key: 'technicalFindings',   label: 'Technical findings',       hint: 'Summary of automated and manual test results', multiline: true },
    { key: 'nonAccessibleContent',label: 'Non-accessible content',   hint: 'Known barriers and planned remediation', multiline: true },
    { key: 'feedbackMechanism',   label: 'Feedback mechanism',       hint: 'How users can report accessibility barriers', multiline: true },
    { key: 'enforcementProcedure',label: 'Enforcement procedure',    hint: 'Relevant enforcement body or process', multiline: true },
    { key: 'additionalNotes',     label: 'Additional notes',         hint: 'Any other relevant information', multiline: true },
  ];

  return (
    <div className="space-y-6">
      {/* DRAFT disclaimer — always shown, cannot be hidden */}
      <div
        className="flex gap-3 rounded-lg border border-amber-300 bg-amber-50 dark:bg-amber-950/40 dark:border-amber-700 p-4"
        role="alert"
        aria-live="polite"
      >
        <AlertTriangle className="h-5 w-5 text-amber-600 dark:text-amber-400 shrink-0 mt-0.5" aria-hidden="true" />
        <p className="text-sm text-amber-800 dark:text-amber-300">{DRAFT_DISCLAIMER}</p>
      </div>

      {/* Status */}
      <div className="flex items-center gap-3">
        <Badge variant="outline">{STATUS_LABELS[status] ?? status}</Badge>
        <Button
          variant="ghost"
          size="sm"
          onClick={() => setPreview((p) => !p)}
          aria-pressed={preview}
        >
          {preview ? 'Edit' : 'Preview'}
        </Button>
      </div>

      {preview ? (
        /* Plain-text preview — no HTML rendered */
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Statement preview (plain text)</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3 text-sm">
            {FIELDS.map(({ key, label }) =>
              content[key] ? (
                <div key={key}>
                  <p className="font-medium text-xs text-muted-foreground uppercase tracking-wide mb-1">{label}</p>
                  <p className="whitespace-pre-wrap">{content[key]}</p>
                </div>
              ) : null,
            )}
          </CardContent>
        </Card>
      ) : (
        /* Edit form */
        <div className="space-y-4">
          {FIELDS.map(({ key, label, hint, multiline }) => (
            <div key={key} className="space-y-1.5">
              <Label htmlFor={`stmt-${key}`}>{label}</Label>
              {multiline ? (
                <Textarea
                  id={`stmt-${key}`}
                  value={content[key] ?? ''}
                  onChange={(e) => update(key, e.target.value)}
                  placeholder={hint}
                  rows={3}
                  className="text-sm"
                />
              ) : (
                <Input
                  id={`stmt-${key}`}
                  value={content[key] ?? ''}
                  onChange={(e) => update(key, e.target.value)}
                  placeholder={hint}
                  className="text-sm"
                />
              )}
            </div>
          ))}
        </div>
      )}

      {/* Save actions */}
      <div className="flex gap-2">
        <Button onClick={handleSave} disabled={saving}>
          {saving ? 'Saving…' : 'Save statement'}
        </Button>
        {status === 'draft' && (
          <Button
            variant="outline"
            onClick={() => { setStatus('ready_for_review'); }}
            disabled={saving}
          >
            Mark ready for review
          </Button>
        )}
      </div>
    </div>
  );
}
