/**
 * Accessibility Statement Draft Generator
 *
 * Generates DRAFT accessibility statements for user review.
 *
 * CRITICAL LANGUAGE CONSTRAINTS:
 *  - Every generated statement MUST include the DRAFT disclaimer.
 *  - Never use: "guaranteed compliance", "certified", "legally compliant",
 *    "immune from fines", "100% compliant", "government certification".
 *  - Always include: "DRAFT — Review before publication",
 *    "This statement was generated as a starting template",
 *    "Manual review required before publication".
 */

/** Always present in every generated statement — never remove. */
export const STATEMENT_DISCLAIMER =
  'DRAFT — Review before publication. This statement was generated by WebScore as a starting template. ' +
  'It must be reviewed by a qualified person before publication. WebScore does not provide legal advice. ' +
  'Automated testing alone cannot certify conformance with accessibility standards.';

export interface StatementKnownIssue {
  title:             string;
  impact:            string;
  alternativeAccess?: string;
}

export interface AccessibilityStatementContent {
  organizationName:   string;
  siteName:           string;
  siteUrl:            string;
  jurisdictionId:     string;
  standardName:       string;
  assessmentDate:     string;
  currentStatusWording: string;
  knownIssues:        StatementKnownIssue[];
  remediationPlan:    string;
  contactEmail?:      string;
  contactFormUrl?:    string;
  contactPhone?:      string;
  postalAddress?:     string;
  supportUrl?:        string;
  statementDate:      string;
  nextReviewDate:     string;
  templateVersion:    string;
  disclaimer:         string;
}

export interface StatementTemplate {
  jurisdictionId:   string;
  version:          string;
  requiredSections: string[];
  reviewInterval:   string;
  disclaimer:       string;
}

export const STATEMENT_TEMPLATES: Record<string, StatementTemplate> = {
  eu_eaa: {
    jurisdictionId:   'eu_eaa',
    version:          '2026.1',
    requiredSections: ['scope', 'conformance_status', 'non_accessible_content', 'alternatives', 'feedback', 'enforcement', 'preparation_date'],
    reviewInterval:   '12 months',
    disclaimer:       STATEMENT_DISCLAIMER,
  },
  eu_public_sector: {
    jurisdictionId:   'eu_public_sector',
    version:          '2026.1',
    requiredSections: ['scope', 'conformance_status', 'non_accessible_content', 'disproportionate_burden', 'alternatives', 'feedback', 'enforcement', 'preparation_date'],
    reviewInterval:   '12 months',
    disclaimer:       STATEMENT_DISCLAIMER,
  },
  uk_public_sector: {
    jurisdictionId:   'uk_public_sector',
    version:          '2026.1',
    requiredSections: ['scope', 'conformance_status', 'non_accessible_content', 'disproportionate_burden', 'alternatives', 'feedback', 'enforcement', 'preparation_date'],
    reviewInterval:   '12 months',
    disclaimer:       STATEMENT_DISCLAIMER,
  },
  us_section_508: {
    jurisdictionId:   'us_section_508',
    version:          '2026.1',
    requiredSections: ['scope', 'conformance_status', 'known_issues', 'contact', 'preparation_date'],
    reviewInterval:   '12 months',
    disclaimer:       STATEMENT_DISCLAIMER,
  },
  us_ada_title_ii: {
    jurisdictionId:   'us_ada_title_ii',
    version:          '2026.1',
    requiredSections: ['scope', 'conformance_status', 'known_issues', 'contact', 'preparation_date'],
    reviewInterval:   '12 months',
    disclaimer:       STATEMENT_DISCLAIMER,
  },
};

/** Fallback template used when jurisdiction has no specific template. */
const FALLBACK_TEMPLATE: StatementTemplate = {
  jurisdictionId:   'generic',
  version:          '2026.1',
  requiredSections: ['scope', 'conformance_status', 'known_issues', 'contact', 'preparation_date'],
  reviewInterval:   '12 months',
  disclaimer:       STATEMENT_DISCLAIMER,
};

export interface GenerateStatementOpts {
  profile: {
    name:             string;
    targetMarkets:    string[];
    selectedStandards: string[];
  };
  assessment: {
    completedAt?:      string;
    coveragePercent:   number;
    riskResult?:       { label: string } | null;
  };
  jurisdiction: {
    id:                string;
    name:              string;
    technicalStandard?: string;
  };
  /** Open findings to list in the known-issues section (max 20). */
  knownFindings:  { title: string; impact: string }[];
  contactInfo:    Partial<AccessibilityStatementContent>;
}

/**
 * Generate a DRAFT accessibility statement for user review.
 *
 * The output always includes STATEMENT_DISCLAIMER and never claims
 * certification, legal immunity, or government-authority approval.
 */
export function generateStatementDraft(opts: GenerateStatementOpts): AccessibilityStatementContent {
  const now = new Date();
  const reviewDate = new Date(now);
  reviewDate.setFullYear(reviewDate.getFullYear() + 1);

  const template =
    STATEMENT_TEMPLATES[opts.jurisdiction.id.toLowerCase()] ?? FALLBACK_TEMPLATE;

  const knownIssues: StatementKnownIssue[] = opts.knownFindings
    .slice(0, 20)
    .map((f) => ({
      title:             f.title,
      impact:            f.impact,
      alternativeAccess: 'Please contact us for an accessible alternative.',
    }));

  // Neutral wording — never claims conformance or legal status
  const currentStatusWording =
    opts.assessment.coveragePercent >= 80
      ? 'Partially conformant — some content does not fully conform to the applicable standard. Known accessibility issues are listed below.'
      : 'Non-conformant or insufficient test coverage — the automated assessment did not cover enough of the site to determine conformance status. Manual review is required.';

  return {
    organizationName:     opts.contactInfo.organizationName ?? '[Organization Name]',
    siteName:             opts.profile.name,
    siteUrl:              opts.contactInfo.siteUrl ?? '[Site URL]',
    jurisdictionId:       opts.jurisdiction.id,
    standardName:
      opts.jurisdiction.technicalStandard ??
      opts.profile.selectedStandards[0] ??
      'WCAG 2.1 AA',
    assessmentDate:
      opts.assessment.completedAt?.split('T')[0] ??
      now.toISOString().split('T')[0],
    currentStatusWording,
    knownIssues,
    remediationPlan:
      opts.contactInfo.remediationPlan ??
      'We are actively working to resolve identified accessibility issues. ' +
      'Please contact us for updates on our remediation timeline.',
    contactEmail:    opts.contactInfo.contactEmail,
    contactFormUrl:  opts.contactInfo.contactFormUrl,
    contactPhone:    opts.contactInfo.contactPhone,
    postalAddress:   opts.contactInfo.postalAddress,
    supportUrl:      opts.contactInfo.supportUrl,
    statementDate:      now.toISOString().split('T')[0],
    nextReviewDate:     reviewDate.toISOString().split('T')[0],
    templateVersion:    template.version,
    disclaimer:         STATEMENT_DISCLAIMER,
  };
}
