import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Service',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0A0A0F] text-[#F8FAFC]">
      <div className="max-w-3xl mx-auto px-4 py-12">
        <Link href="/" className="inline-flex items-center gap-1.5 text-sm text-[#94A3B8] hover:text-white transition-colors mb-8">
          <ArrowLeft className="h-4 w-4" />
          Back
        </Link>

        <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
        <p className="text-sm text-[#94A3B8] mb-10">Last updated: May 2026</p>

        <div className="space-y-10 text-[#94A3B8] leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance</h2>
            <p>By accessing or using Website Analyzer (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree to all of these terms, you may not use the Service. We reserve the right to update these terms at any time, with notice provided via email or in-app notification.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. Service Description</h2>
            <p>Website Analyzer is a SaaS platform that analyzes publicly accessible websites for performance, accessibility, SEO quality, and AI-readiness. Analysis results are generated using automated tools and AI models. Results are provided for informational purposes only and do not constitute professional advice.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. User Accounts</h2>
            <p>You are responsible for maintaining the security of your account credentials. You must not share your account with others. You are responsible for all activity that occurs under your account. You must provide accurate information when creating an account and keep it up to date.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. Acceptable Use</h2>
            <p className="mb-3">You agree not to use the Service to:</p>
            <ul className="list-disc list-inside space-y-1.5 ml-2">
              <li>Analyze websites without authorization from their owners</li>
              <li>Conduct denial-of-service attacks or deliberately overload the analysis system</li>
              <li>Circumvent rate limits or access controls</li>
              <li>Resell API access without our express written permission</li>
              <li>Use the Service for any unlawful purpose</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. Credits & Billing</h2>
            <p>The Free plan includes 3 analysis credits per month. Paid plans include additional credits as described on the pricing page. Credits are consumed when an analysis is submitted. Credits that are not used within a billing period do not roll over. Subscriptions are billed monthly in advance. You may cancel your subscription at any time; cancellation takes effect at the end of the current billing period.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. Intellectual Property</h2>
            <p>The Service and its original content, features, and functionality are owned by WebAnalyzer and are protected by applicable intellectual property laws. Analysis reports generated by the Service may be used freely by the account holder for their own purposes. You retain ownership of any content you submit to the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">7. Limitation of Liability</h2>
            <p>The Service is provided &quot;as is&quot; without warranties of any kind. We do not guarantee that analysis results are accurate, complete, or suitable for any particular purpose. To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, or consequential damages arising out of your use of the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">8. Termination</h2>
            <p>We may suspend or terminate your account immediately if you violate these Terms. You may delete your account at any time from the Settings page. Upon termination, your data will be deleted in accordance with our Privacy Policy.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">9. Governing Law</h2>
            <p>These Terms are governed by and construed in accordance with applicable law. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the competent courts.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
