'use client';

import { useState } from 'react';
import { toast } from 'sonner';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';

interface BrandingFormProps {
  initialAgencyName: string;
  initialBrandColor: string;
  initialShowPoweredBy: boolean;
  isPro: boolean;
}

export function BrandingForm({
  initialAgencyName,
  initialBrandColor,
  initialShowPoweredBy,
  isPro,
}: BrandingFormProps) {
  const [agencyName, setAgencyName]       = useState(initialAgencyName);
  const [brandColor, setBrandColor]       = useState(initialBrandColor);
  const [showPoweredBy, setShowPoweredBy] = useState(initialShowPoweredBy);
  const [saving, setSaving]               = useState(false);

  const handleSave = async () => {
    setSaving(true);
    try {
      const res = await fetch('/api/user/branding', {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ agencyName, brandColor, showPoweredBy }),
      });

      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error((data as any).error ?? 'Failed to save branding settings');
      }

      toast.success('Branding settings saved');
    } catch (err: unknown) {
      toast.error(err instanceof Error ? err.message : 'Failed to save branding settings');
    } finally {
      setSaving(false);
    }
  };

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center gap-2">
          <CardTitle>White-label Branding</CardTitle>
          {isPro && (
            <Badge variant="default" className="text-xs">Pro</Badge>
          )}
        </div>
      </CardHeader>
      <CardContent className="space-y-5">

        {/* Agency name */}
        <div className="space-y-1.5">
          <Label htmlFor="agencyName">Agency Name</Label>
          <Input
            id="agencyName"
            type="text"
            placeholder="Your Agency Name"
            maxLength={60}
            value={agencyName}
            onChange={(e) => setAgencyName(e.target.value)}
          />
          <p className="text-xs text-muted-foreground">
            Shown in the header of exported PDF reports.
          </p>
        </div>

        {/* Brand color */}
        <div className="space-y-1.5">
          <Label htmlFor="brandColor">Brand Color</Label>
          <div className="flex items-center gap-3 p-3 bg-background border border-border rounded-lg">
            <input
              id="brandColor"
              type="color"
              value={brandColor}
              onChange={(e) => setBrandColor(e.target.value)}
              className="h-10 w-10 cursor-pointer rounded border border-border bg-background p-0.5"
              title="Pick brand color"
            />
            <div
              className="h-10 w-24 rounded border border-border"
              style={{ backgroundColor: brandColor }}
              aria-label={`Color preview: ${brandColor}`}
            />
            <span className="font-mono text-sm text-muted-foreground">{brandColor}</span>
          </div>
          <p className="text-xs text-muted-foreground">
            Used for headings and accents in PDF reports.
          </p>
        </div>

        {/* Show powered by toggle */}
        <div className="space-y-1.5">
          <div className="flex items-center gap-3">
            <input
              id="showPoweredBy"
              type="checkbox"
              checked={showPoweredBy}
              onChange={(e) => setShowPoweredBy(e.target.checked)}
              className="h-4 w-4 cursor-pointer rounded accent-indigo-500"
            />
            <Label htmlFor="showPoweredBy" className="cursor-pointer">
              Show &quot;Generated by WebAnalyzer&quot;
            </Label>
          </div>
          <p className="text-xs text-muted-foreground">
            When off, reports show only your agency name (Pro/Agency plan).
          </p>
        </div>

        <Button
          onClick={handleSave}
          disabled={saving}
          className="bg-gradient-to-r from-indigo-500 to-violet-500 text-white hover:from-indigo-400 hover:to-violet-400"
        >
          {saving ? 'Saving…' : 'Save Branding'}
        </Button>
      </CardContent>
    </Card>
  );
}
